export const ASSET_STATUS = {
  ACTIVE: "ACTIVE",
  UNDER_REPAIR: "UNDER_REPAIR",
  FAULTY: "FAULTY",
  IN_STORAGE: "IN_STORAGE",
  MISSING: "MISSING",
  DISPOSED: "DISPOSED",
  DONATED: "DONATED",
  SOLD: "SOLD",
} as const;

export const ASSET_CONDITION = {
  EXCELLENT: "EXCELLENT",
  GOOD: "GOOD",
  FAIR: "FAIR",
  POOR: "POOR",
  CRITICAL: "CRITICAL",
} as const;

export const MOVEMENT_TYPE = {
  BRANCH_TRANSFER: "BRANCH_TRANSFER",
  STORAGE_TRANSFER: "STORAGE_TRANSFER",
  STAFF_ASSIGNMENT: "STAFF_ASSIGNMENT",
  ROOM_TRANSFER: "ROOM_TRANSFER",
  SHELF_TRANSFER: "SHELF_TRANSFER",
  DEPARTMENT_TRANSFER: "DEPARTMENT_TRANSFER",
} as const;

export const RECOMMENDATION_STATE = {
  HEALTHY: "HEALTHY",
  APPROACHING: "APPROACHING",
  OVERDUE: "OVERDUE",
} as const;

export const DOCUMENT_TYPE = {
  RECEIPT: "RECEIPT",
  WARRANTY_CARD: "WARRANTY_CARD",
  MANUAL: "MANUAL",
  SERVICE_REPORT: "SERVICE_REPORT",
  MAINTENANCE_INVOICE: "MAINTENANCE_INVOICE",
  OTHER: "OTHER",
} as const;

export const ASSET_REQUEST_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  FULFILLED: "FULFILLED",
} as const;

export const ASSET_REQUEST_URGENCY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

export const MAINTENANCE_STATUS = {
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
} as const;

export const DISPOSAL_METHOD = {
  DONATED: "DONATED",
  SOLD: "SOLD",
  DISPOSED: "DISPOSED",
} as const;

export const DEPRECIATION_METHOD = {
  STRAIGHT_LINE: "STRAIGHT_LINE",
} as const;
