export const ASSET_STATUS = {
  ACTIVE: "ACTIVE",
  UNDER_REPAIR: "UNDER_REPAIR",
  FAULTY: "FAULTY",
  IN_STORAGE: "IN_STORAGE",
  MISSING: "MISSING",
  DISPOSED: "DISPOSED",
} as const;

export const ASSET_CONDITION = {
  EXCELLENT: "EXCELLENT",
  GOOD: "GOOD",
  FAIR: "FAIR",
  POOR: "POOR",
  CRITICAL: "CRITICAL",
} as const;

export const MOVEMENT_TYPE = {
  BRANCH_TRANSFER: "BRANCH_TRANSFER",
  STORAGE_TRANSFER: "STORAGE_TRANSFER",
  STAFF_ASSIGNMENT: "STAFF_ASSIGNMENT",
  ROOM_TRANSFER: "ROOM_TRANSFER",
  SHELF_TRANSFER: "SHELF_TRANSFER",
} as const;

export const RECOMMENDATION_STATE = {
  HEALTHY: "HEALTHY",
  APPROACHING: "APPROACHING",
  OVERDUE: "OVERDUE",
} as const;

export const DOCUMENT_TYPE = {
  RECEIPT: "RECEIPT",
  WARRANTY_CARD: "WARRANTY_CARD",
  MANUAL: "MANUAL",
  SERVICE_REPORT: "SERVICE_REPORT",
  OTHER: "OTHER",
} as const;
