export const APP_ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SCAN: "/scan",
  USAGE_MANUAL: "/usage-manual",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  ASSET_REQUESTS: "/requests",
  DASHBOARD: "/dashboard",
  ASSETS: "/assets",
  DOCUMENTS: "/documents",
  LOCATIONS: "/locations",
  MAINTENANCE: "/maintenance",
  REPLACEMENT: "/replacement",
  REPORTS: "/reports",
  BRANCHES: "/branches",
  USERS: "/users",
  STAFF: "/staff",
  SETTINGS: "/settings",
  SETTINGS_ORGANIZATION: "/settings/organization",
  SETTINGS_BRANCHES: "/settings/branches",
  SETTINGS_CATEGORIES: "/settings/categories",
  SETTINGS_VENDORS: "/settings/vendors",
  SETTINGS_LOCATIONS: "/settings/locations",
  SETTINGS_FEATURES: "/settings/features",
  SETTINGS_POLICIES: "/settings/policies",
  SETTINGS_DEPRECIATION: "/settings/depreciation",
  SETTINGS_REMINDERS: "/settings/reminders",
  SETTINGS_AUDIT: "/settings/audit",
} as const;

export const API_ROUTES = {
  EXPORT_REPORTS: "/api/reports/export",
  OFFLINE_SYNC: "/api/offline/sync",
  REMINDERS_DISPATCH: "/api/reminders/dispatch",
  CSV_IMPORT: "/api/assets/import",
  CSV_IMPORT_TEMPLATE: "/api/assets/import/template",
} as const;
