export const IMPORT_STATUS = {
  PENDING: "PENDING",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const REMINDER_TYPE = {
  WARRANTY_EXPIRY: "WARRANTY_EXPIRY",
  REPLACEMENT_DUE: "REPLACEMENT_DUE",
  MAINTENANCE_DUE: "MAINTENANCE_DUE",
} as const;
